### ISSUE TITLE
Error uploading images

### ISSUE THREAD

**Issue by tatsukamijo** [DavidPL1/assembly_example#28]
When we tried to upload the solution images, we encountered an error.

I guess it might be caused by the large file size (11GB each) or the file format.
Do you have any idea what was wrong?

We created the `.tar` file using the `docker save` command as follows:
`docker save -o utokyo_assembly_plugging.tar utokyo/assembly_plugging`

![image](https://user-images.githubusercontent.com/81934527/236472533-740dd2cc-d476-4514-9fbc-ff12dd5999b1.png)

**Comment by DavidPL1** [comment]
I don't know if it fixes the actual uploading issue, but you can pipe the image into gzip to compress the tar like this:

```bash
docker save utokyo/assembly_plugging | gzip > utokyo_assembly_plugging.tar.gz
```

**Comment by balandbal** [comment]
I am looking into whether it results from a limitation on SharePoint's end and whether there is another uploading platform we could use as a fallback.

Update:
I uploaded 3x13GB files in parallel via a SharePoint link without a problem.
@tatsukamijo, could it be something due to internet connectivity? Was there progress after retrying?

Nonetheless, I am now checking the upload process from Tokyo via a VPN, just in case.

**Comment by tatsukamijo** [comment]
Thank you for your reply!

We retried several times that day but ended up failing.
However, when we compressed `.tar` file into `.tar.gz` we were able to upload both images successfully.
We are actually unsure about what caused this problem.
