### ISSUE TITLE
mujoco_ros_control getting reset while executing a plan causes execution to fail

### ISSUE THREAD

**Issue by abhishek47kashyap** [DavidPL1/assembly_example#3]
Successfully computed plans sometimes result in failed executions: execution begins but stops short of the goal with these logs:
```
[ INFO] [1677603355.509089828, 14.138000000]: Execution request received
[ INFO] [1677603361.961577291, 15.421000000] [ros.mujoco_ros_control.mujoco_ros_control] [/mujoco_server]: Resetting mujoco_ros_control due to time reset
[ INFO] [1677603361.964809774, 15.423000000]: Controller 'effort_joint_trajectory_controller' successfully finished
[ WARN] [1677603361.965065657, 15.424000000]: Controller handle effort_joint_trajectory_controller reports status PREEMPTED
[ INFO] [1677603361.965187640, 15.424000000]: Completed trajectory execution with status PREEMPTED ...
[ INFO] [1677603361.965381800, 15.424000000]: Execution completed: PREEMPTED
```

When execution does proceed to completion, the logs are:
```
[ INFO] [1677603379.451140313, 18.963000000]: Execution request received
[ INFO] [1677603382.033941919, 19.475000000]: Controller 'effort_joint_trajectory_controller' successfully finished
[ INFO] [1677603382.314629639, 19.503000000]: Completed trajectory execution with status SUCCEEDED ...
[ INFO] [1677603382.314818036, 19.503000000]: Execution completed: SUCCEEDED
```

So `mujoco_ros_control` getting reset _before execution completes_ is responsible for trajectory execution's status being reported as preempted, which does make sense. Why on some occasions does `mujoco_ros_control` get reset while an execution is underway? What is the "time reset" as stated in the log and what causes it?

I've got `eval_mode` set to `false` (and `difficulty_level` as `1`, in case relevant but I'd be surprised if it is). I'm trying to move to a pose from the [assembly_screw example](https://github.com/DavidPL1/assembly_example/blob/main/docker/assembly_example_ros/nodes/assembly_screw):
```
    pose_goal = move_group.get_current_pose().pose    // robot EE when s4dx/assembly_server starts up
    pose_goal.position.x = 0.5
    pose_goal.position.y = -0.2
    pose_goal.position.z = 0.6
```

Any suggestions on how to overcome this or pointers on possible mistakes made by me would be very appreciated.

**Comment by DavidPL1** [comment]
Thanks for reporting this issue.

> What is the "time reset" as stated in the log and what causes it?

Our simulation can be reset by the user, which causes the ROS time to be reset to 0. This requires some special handling e.g. clearing message buffers among other things, because otherwise involved ROS components would ignore new messages with timestamps they have already seen. The log message present in your log is triggered when mujoco_ros_control detects that the current ROS time is older than the ROS time when it ran the last control update, concluding a time reset must have happened.
This leads to preemption of the currently running task, as you also noted.

> Why on some occasions does mujoco_ros_control get reset while an execution is underway? 

This should not happen unless a simulation reset is triggered manually and ROS time is reset. In both your logs the ROS time keeps incrementing, so no actual reset is triggered.

We have to reproduce the issue on our side and backtrack the cause. 
You do seem to have a very low real-time factor of 0.19. This might be an indicator that this issue is related to high CPU load.
I can update the docker server image for you to configure a target real-time factor, you could try to set it below your apparent upper bound of 0.19 and report if you are able to reproduce the error.

> I've got eval_mode set to false (and difficulty_level as 1, in case relevant but I'd be surprised if it is). I'm trying to move to a pose from the [assembly_screw example](https://github.com/DavidPL1/assembly_example/blob/main/docker/assembly_example_ros/nodes/assembly_screw)

It seems the issue is rooted somewhere in [mujoco_ros_control](https://github.com/ubi-agni/mujoco_ros_pkgs/tree/noetic-devel/mujoco_ros_control) or [mujoco_ros](https://github.com/ubi-agni/mujoco_ros_pkgs/tree/noetic-devel/mujoco_ros). The loaded scenario and difficulty setting should not make a difference here.

We'll keep you posted. In the meantime, if you are able to pinpoint more details about when this error happens please report them in this issue.

**Comment by DavidPL1** [comment]
As explained in ubi-agni/mujoco_ros_pkgs#20, this issue should be fixed by commit https://github.com/ubi-agni/mujoco_ros_pkgs/commit/24a61540a7e9dec1f84d45169550316a80fbd614.
I'm about to build an updated docker image version and will notify you, once it is uploaded.

I ran some tests and am rather sure you should not experience any more preempts because of this particular error, but I'll leave the issue open until you have tested the new version and confirmed that the fix works.

**Comment by DavidPL1** [comment]
Version 1.1 of the docker image was now added to the cloud you have been provided access to. Please let me know if everything now works for you or if you experience other issues. 
Heavy load should not trigger this anymore, so you should also be fine with all your visualizations active.

**Comment by abhishek47kashyap** [comment]
I can confirm version 1.1 does not have this problem. I verified with all my visualizations from before active _and_ with 20 out of 32 cores stressed. Thank you for providing a new image with the hotfix.

**Comment by Daviesss** [comment]
> I can confirm version 1.1 does not have this problem. I verified with all my visualizations from before active _and_ with 20 out of 32 cores stressed. Thank you for providing a new image with the hotfix.

Hello , i am having problem integrating mujoco_ros_control pkg for control . How did you get it to work ?
